### ISSUE TITLE
Runtime disconnected (FaceFusion became detectable)

### ISSUE THREAD

**Issue by nvm01** [Nick088Official/FaceFusion-Online-Ports#18]
Hello!
It seems that the Next branch is detected no matter what tunneling is used. You can't even open the interface that colab will shutdown the runtime.
I'll try with master branch too and I'll update the thread.

**Comment by Nick088Official** [comment]
This seems to be happening only on the next branch for me, i think due to the run file being named facefusion.py which i can obfuscate.
What about you? I was able to run fine the master branch for like 30 mins

**Comment by Nick088Official** [comment]
I just pushed another update which should fix the next branch, i ran it for over 20 mins and got no issues. But let me know

**Comment by Katsukipp** [comment]
i have same problem, but i am using master branch

huft, last month before google detected facefusion  and terminate the process it was really good and normal and 


and i got this..

![Screenshot (5)](https://github.com/user-attachments/assets/873a69ad-1bc4-4056-a94d-9da25a4870eb)

**Comment by Katsukipp** [comment]
> i have same problem, but i am using master branch
> 
> huft, last month before google detected facefusion and terminate the process it was really good and normal and
> 
> and i got this..
> 
> ![Screenshot (5)](https://private-user-images.githubusercontent.com/182143800/369493470-873a69ad-1bc4-4056-a94d-9da25a4870eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NTI5MTUsIm5iZiI6MTcyNjg1MjYxNSwicGF0aCI6Ii8xODIxNDM4MDAvMzY5NDkzNDcwLTg3M2E2OWFkLTFiYzQtNDA1Ni1hOTRkLTlkYTI1YTQ4NzBlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxNzE2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTBjZTJlZTQzYTRjNzUxOTQxMGI3N2RlZGZkMDZjYWI3NGRlZWZlNTAxNzI3NmQxNjRlNDY0NzQ5MjBmNjcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9WuqBqm6NEPC-SroB3ySdHNoy6BqPm-CKiO0DzObJrY)

and i realized it get disconnected everytime the process start merging video... i've tried this two times, and get same problem that always disconnected at merging process

i think  google detected the merging proccess code that they doesnt allowed it

i hope you can fix it

**Comment by Katsukipp** [comment]
> I can confirm that it works good right now! Keep up the good work! No disconnections.
> 
> Edit: Tried the latest notebook.

which branch is it?
and may i know how long is your video?

because i still get disconnected when its on merging process

**Comment by nvm01** [comment]
> > I can confirm that it works good right now! Keep up the good work! No disconnections.
> > Edit: Tried the latest notebook.
> 
> which branch is it? and may i know how long is your video?
> 
> because i still get disconnected when its on merging process

This notebook -> it automatically contains the next branch: https://github.com/Nick088Official/FaceFusion-Online-Ports/blob/main/FaceFusion_UI.ipynb

The video has almost 2 minutes.

**Comment by Katsukipp** [comment]
> > I can confirm that it works good right now! Keep up the good work! No disconnections.
> > Edit: Tried the latest notebook.
> 
> which branch is it? and may i know how long is your video?
> 
> because i still get disconnected when its on merging process



hmm, seems like its been updated,
 the one i used (3 or 4 hours ago) is contain branch selection, and now i check it, theres no those selection anymore, 


i'll try the new no ui colab  and i'll update the thread

**Comment by Nick088Official** [comment]
> > I can confirm that it works good right now! Keep up the good work! No disconnections.
> > Edit: Tried the latest notebook.
> 
> which branch is it? and may i know how long is your video?
> 
> because i still get disconnected when its on merging process

I just updated it and was able to process a short video, it ran for 10 mins and worked all fine, let me know!

**Comment by Nick088Official** [comment]
> > > I can confirm that it works good right now! Keep up the good work! No disconnections.
> > > Edit: Tried the latest notebook.
> > 
> > 
> > which branch is it? and may i know how long is your video?
> > because i still get disconnected when its on merging process
> 
> This notebook -> it automatically contains the next branch: https://github.com/Nick088Official/FaceFusion-Online-Ports/blob/main/FaceFusion_UI.ipynb
> 
> The video has almost 2 minutes.



> I can confirm that it works good right now! Keep up the good work! No disconnections.
> 
> Edit: Tried the latest notebook.

That's good to hear!

**Comment by nvm01** [comment]
Unlucky, it doesn't work. It disconnected exactly after generating the video, so I didn't even have time to save it...
Ran for 27 mins 39 seconds. I don't know if the runtime was disconnected because they detected the saved video...

![not working - Copy](https://github.com/user-attachments/assets/b6c3f90d-3d18-4b40-8a42-18ba7cd68973)

**Comment by Nick088Official** [comment]
> > > I can confirm that it works good right now! Keep up the good work! No disconnections.
> > > Edit: Tried the latest notebook.
> > 
> > 
> > which branch is it? and may i know how long is your video?
> > because i still get disconnected when its on merging process
> 
> This notebook -> it automatically contains the next branch: https://github.com/Nick088Official/FaceFusion-Online-Ports/blob/main/FaceFusion_UI.ipynb
> 
> The video has almost 2 minutes.

Btw, i removed the branch option as in facefusion they just merged the 'next' branch into the 'master' one (basically 3.0.0 update) so the 'next' doesn't exist anymore

**Comment by Nick088Official** [comment]
> Unlucky, it doesn't work. It disconnected exactly after generating the video, so I didn't even have time to save it... Ran for 27 mins 39 seconds. I don't know if the runtime was disconnected because they detected the saved video...
> 
> ![not working - Copy](https://private-user-images.githubusercontent.com/155398669/369505115-b6c3f90d-3d18-4b40-8a42-18ba7cd68973.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NTUyNzIsIm5iZiI6MTcyNjg1NDk3MiwicGF0aCI6Ii8xNTUzOTg2NjkvMzY5NTA1MTE1LWI2YzNmOTBkLTNkMTgtNGI0MC04YTQyLTE4YmE3Y2Q2ODk3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxNzU2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWM2NWM0ZTQzYTBiZjk4NmVkMWE1N2JlYjUyMjlhNzMxNjAxZGZkOGRmNjcwMzQ5MzEwYWUxZWQzYWFjYTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jIJY1dKIEh4SueD8Xfji28a8UC8osXotHqBNdByzVRE)

Could you please retry on an alt account? Sometimes it's random how it gets detected (like for some account it could get detected for some couldn't), because i ran it fine for 30 mins

**Comment by nvm01** [comment]
> > Unlucky, it doesn't work. It disconnected exactly after generating the video, so I didn't even have time to save it... Ran for 27 mins 39 seconds. I don't know if the runtime was disconnected because they detected the saved video...
> > ![not working - Copy](https://private-user-images.githubusercontent.com/155398669/369505115-b6c3f90d-3d18-4b40-8a42-18ba7cd68973.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NTUyNzIsIm5iZiI6MTcyNjg1NDk3MiwicGF0aCI6Ii8xNTUzOTg2NjkvMzY5NTA1MTE1LWI2YzNmOTBkLTNkMTgtNGI0MC04YTQyLTE4YmE3Y2Q2ODk3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxNzU2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWM2NWM0ZTQzYTBiZjk4NmVkMWE1N2JlYjUyMjlhNzMxNjAxZGZkOGRmNjcwMzQ5MzEwYWUxZWQzYWFjYTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jIJY1dKIEh4SueD8Xfji28a8UC8osXotHqBNdByzVRE)
> 
> Could you please retry on an alt account? Sometimes it's random how it gets detected (like for some account it could get detected for some couldn't), because i ran it fine for 30 mins

Did you actually render a video and saved it? Or you just kept facefusion opened?

**Comment by nvm01** [comment]
> > Unlucky, it doesn't work. It disconnected exactly after generating the video, so I didn't even have time to save it... Ran for 27 mins 39 seconds. I don't know if the runtime was disconnected because they detected the saved video...
> > ![not working - Copy](https://private-user-images.githubusercontent.com/155398669/369505115-b6c3f90d-3d18-4b40-8a42-18ba7cd68973.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NTUyNzIsIm5iZiI6MTcyNjg1NDk3MiwicGF0aCI6Ii8xNTUzOTg2NjkvMzY5NTA1MTE1LWI2YzNmOTBkLTNkMTgtNGI0MC04YTQyLTE4YmE3Y2Q2ODk3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxNzU2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWM2NWM0ZTQzYTBiZjk4NmVkMWE1N2JlYjUyMjlhNzMxNjAxZGZkOGRmNjcwMzQ5MzEwYWUxZWQzYWFjYTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jIJY1dKIEh4SueD8Xfji28a8UC8osXotHqBNdByzVRE)
> 
> Could you please retry on an alt account? Sometimes it's random how it gets detected (like for some account it could get detected for some couldn't), because i ran it fine for 30 mins

Will try that anyway, but I don't really think that the problem is from the google account.

**Comment by Nick088Official** [comment]
> > > Unlucky, it doesn't work. It disconnected exactly after generating the video, so I didn't even have time to save it... Ran for 27 mins 39 seconds. I don't know if the runtime was disconnected because they detected the saved video...
> > > ![not working - Copy](https://private-user-images.githubusercontent.com/155398669/369505115-b6c3f90d-3d18-4b40-8a42-18ba7cd68973.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NTUyNzIsIm5iZiI6MTcyNjg1NDk3MiwicGF0aCI6Ii8xNTUzOTg2NjkvMzY5NTA1MTE1LWI2YzNmOTBkLTNkMTgtNGI0MC04YTQyLTE4YmE3Y2Q2ODk3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxNzU2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWM2NWM0ZTQzYTBiZjk4NmVkMWE1N2JlYjUyMjlhNzMxNjAxZGZkOGRmNjcwMzQ5MzEwYWUxZWQzYWFjYTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jIJY1dKIEh4SueD8Xfji28a8UC8osXotHqBNdByzVRE)
> > 
> > 
> > Could you please retry on an alt account? Sometimes it's random how it gets detected (like for some account it could get detected for some couldn't), because i ran it fine for 30 mins
> 
> Did you actually render a video and saved it? Or you just kept facefusion opened?

yes, actually process it and save it
![image](https://github.com/user-attachments/assets/890d8eb7-7ce8-46ea-ab40-3d6d2f55fb0b)

**Comment by Nick088Official** [comment]
> > > Unlucky, it doesn't work. It disconnected exactly after generating the video, so I didn't even have time to save it... Ran for 27 mins 39 seconds. I don't know if the runtime was disconnected because they detected the saved video...
> > > ![not working - Copy](https://private-user-images.githubusercontent.com/155398669/369505115-b6c3f90d-3d18-4b40-8a42-18ba7cd68973.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NTUyNzIsIm5iZiI6MTcyNjg1NDk3MiwicGF0aCI6Ii8xNTUzOTg2NjkvMzY5NTA1MTE1LWI2YzNmOTBkLTNkMTgtNGI0MC04YTQyLTE4YmE3Y2Q2ODk3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxNzU2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWM2NWM0ZTQzYTBiZjk4NmVkMWE1N2JlYjUyMjlhNzMxNjAxZGZkOGRmNjcwMzQ5MzEwYWUxZWQzYWFjYTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jIJY1dKIEh4SueD8Xfji28a8UC8osXotHqBNdByzVRE)
> > 
> > 
> > Could you please retry on an alt account? Sometimes it's random how it gets detected (like for some account it could get detected for some couldn't), because i ran it fine for 30 mins
> 
> Will try that anyway, but I don't really think that the problem is from the google account.

generally speaking about banned colabs, some users got banned, some other not. So it really depends by chances

**Comment by Katsukipp** [comment]
@nvm01 have you try the no ui version instead of the ui ver ?

now ia am back here, as before i am not using the latest update,

and with the latest update now i am still getting disconnected whenever it goes to Merging section..
i've tried using different account, and i am still getting disconnected, 
![Screenshot (7) - Copy](https://github.com/user-attachments/assets/f23a71e0-9dd9-4896-8e94-bdcca914438f)

and it has more than 10 minutes video,  2 hours process until it discinected as soon as Merging section started..
it strange because last month it works without promblem even with more than 10 mins videos..
![Screenshot (8) - Copy](https://github.com/user-attachments/assets/4d29b0fd-201e-42a5-ba0a-40602031e496)


@Nick088Official can you test it with 10> min video? but i am not sure its because the duration.. i dont know..

and if i can ask.. is there a way to link google drive file (input files) into ui version colab and also set the output into gdrive ?  and i think that can help @nvm01 to finish processing without download file directly from UI as before he got disconnected

**Comment by Nick088Official** [comment]
> @nvm01 have you try the no ui version instead of the ui ver ?
> 
> now ia am back here, as before i am not using the latest update,
> 
> and with the latest update now i am still getting disconnected whenever it goes to Merging section.. i've tried using different account, and i am still getting disconnected, ![Screenshot (7) - Copy](https://private-user-images.githubusercontent.com/182143800/369587501-f23a71e0-9dd9-4896-8e94-bdcca914438f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTYzMzksIm5iZiI6MTcyNjkxNjAzOSwicGF0aCI6Ii8xODIxNDM4MDAvMzY5NTg3NTAxLWYyM2E3MWUwLTlkZDktNDg5Ni04ZTk0LWJkY2NhOTE0NDM4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxMDUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MWEyMDgxNjMyYjQyNzRjNzEwMzBkMjNhOTFhYjY5NThjYTRmOTNhNmE1MmY5YTQwN2JjNmY2MTBlM2VjY2UyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WlXK2UfAuLJbVo1boKs7hBVxIvEGjX965sFa7pFl8rk)
> 
> and it has more than 10 minutes video, 2 hours process until it discinected as soon as Merging section started.. it strange because last month it works without promblem even with more than 10 mins videos.. ![Screenshot (8) - Copy](https://private-user-images.githubusercontent.com/182143800/369587635-4d29b0fd-201e-42a5-ba0a-40602031e496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTYzMzksIm5iZiI6MTcyNjkxNjAzOSwicGF0aCI6Ii8xODIxNDM4MDAvMzY5NTg3NjM1LTRkMjliMGZkLTIwMWUtNDJhNS1iYTBhLTQwNjAyMDMxZTQ5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxMDUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmVmNjA4MzU4MzA5ZDhmNDYzYWUwZDE5NzI3MDQ4Zjc5ZjE0MzI2YTFlMjBhNGY5ZDZhOGRmY2M5YjgxNDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7fqOjLiZTv-W0pepCmaefck3aeBkfObQ5kA7fFxWqMU)
> 
> @Nick088Official can you test it with 10> min video? but i am not sure its because the duration.. i dont know..

There will always be a kinda low chance of getting detected, some days ago it used to be in 10 mins now it works good for hours.
Also, don't use long videos, max 1 minute long (split the video) for less chance of losing progress (as said in one of the tips, because it swaps the face per frame and that can take alot with much fps and long videos). If you really don't wanna split it you could else be lucky and hope it works for that period of time (as the detection is really random, even before these recent detection changes, there was some that could run it for 4 hours and others who could get detected before, and as seen in https://github.com/Nick088Official/FaceFusion-Online-Ports/issues/11 I had a report of only 1 person getting banned on 2 accounts, while many others never got banned), or try the [lightning.ai port](https://github.com/Nick088Official/FaceFusion-Online-Ports?tab=readme-ov-file#lightning-ai) that has nothing against web uis & deepfakes.
I will try what I can do to make so it's less detectable as possible but just so you know there will always be a chance to get disconnected for disallowed code just like for all other banned things on colab.

> and if i can ask.. is there a way to link google drive file (input files) into ui version colab and also set the output into gdrive ? and i think that can help @nvm01 to finish processing without download file directly from UI as before he got disconnected

Well, yes that's possible for me to connect google drive for the output, but for the inputs i think its not the best way as you can do it only 1 time per run (like you can set the inputs from google drive only one time per everytime you run the cell, then would have to stop running and re run the cell again for every time you change inputs). I think its better i make so u can optionally connect to drive, making a FF_UI_Outputs folder (so a separated one for ui and no ui colab versions), which will have the processed outputs automatically saved here, and ofc you can put the inputs in the webui. Let me know what you think!

**Comment by Katsukipp** [comment]
> > @nvm01 have you try the no ui version instead of the ui ver ?
> > now ia am back here, as before i am not using the latest update,
> > and with the latest update now i am still getting disconnected whenever it goes to Merging section.. i've tried using different account, and i am still getting disconnected, ![Screenshot (7) - Copy](https://private-user-images.githubusercontent.com/182143800/369587501-f23a71e0-9dd9-4896-8e94-bdcca914438f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTYzMzksIm5iZiI6MTcyNjkxNjAzOSwicGF0aCI6Ii8xODIxNDM4MDAvMzY5NTg3NTAxLWYyM2E3MWUwLTlkZDktNDg5Ni04ZTk0LWJkY2NhOTE0NDM4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxMDUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MWEyMDgxNjMyYjQyNzRjNzEwMzBkMjNhOTFhYjY5NThjYTRmOTNhNmE1MmY5YTQwN2JjNmY2MTBlM2VjY2UyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WlXK2UfAuLJbVo1boKs7hBVxIvEGjX965sFa7pFl8rk)
> > and it has more than 10 minutes video, 2 hours process until it discinected as soon as Merging section started.. it strange because last month it works without promblem even with more than 10 mins videos.. ![Screenshot (8) - Copy](https://private-user-images.githubusercontent.com/182143800/369587635-4d29b0fd-201e-42a5-ba0a-40602031e496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTYzMzksIm5iZiI6MTcyNjkxNjAzOSwicGF0aCI6Ii8xODIxNDM4MDAvMzY5NTg3NjM1LTRkMjliMGZkLTIwMWUtNDJhNS1iYTBhLTQwNjAyMDMxZTQ5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxMDUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmVmNjA4MzU4MzA5ZDhmNDYzYWUwZDE5NzI3MDQ4Zjc5ZjE0MzI2YTFlMjBhNGY5ZDZhOGRmY2M5YjgxNDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7fqOjLiZTv-W0pepCmaefck3aeBkfObQ5kA7fFxWqMU)
> > @Nick088Official can you test it with 10> min video? but i am not sure its because the duration.. i dont know..
> 
> There will always be a kinda low chance of getting detected, some days ago it used to be in 10 mins now it works good for hours. Also, don't use long videos, max 1 minute long (split the video) for less chance of losing progress (as said in one of the tips, because it swaps the face per frame and that can take alot with much fps and long videos). If you really don't wanna split it you could else be lucky and hope it works for that period of time (as the detection is really random, even before these recent detection changes, there was some that could run it for 4 hours and others who could get detected before, and as seen in #11 I had a report of only 1 person getting banned on 2 accounts, while many others never got banned), or try the [lightning.ai port](https://github.com/Nick088Official/FaceFusion-Online-Ports?tab=readme-ov-file#lightning-ai) that has nothing against web uis & deepfakes. I will try what I can do to make so it's less detectable as possible but just so you know there will always be a chance to get disconnected for disallowed code just like for all other banned things on colab.
> 
> > and if i can ask.. is there a way to link google drive file (input files) into ui version colab and also set the output into gdrive ? and i think that can help @nvm01 to finish processing without download file directly from UI as before he got disconnected
> 
> Well, yes that's possible for me to connect google drive for the output, but for the inputs i think its not the best way as you can do it only 1 time per run (like you can set the inputs from google drive only one time per everytime you run the cell, then would have to stop running and re run the cell again for every time you change inputs). I think its better i make so u can optionally connect to drive, making a FF_UI_Outputs folder (so a separated one for ui and no ui colab versions), which will have the processed outputs automatically saved here, and ofc you can put the inputs in the webui. Let me know what you think!



i think thats it
 maybe i should split my project for non ui ver..
 
and as i wanna try UI ver, i would be happy if you can upgrade it  because everytime i upload video direct from ui sometimes it get stuck and takes time for me 
(and for uploading pic, some how it wont load and says "uploading" takes forever for just pic..  and i realized its a bug that i should copy and rename my pic to anything different than fist that failed to upload and it works within a second when i upload  again ) 

 .. it would be better like if i have file in gdrive and just paste the path to the ui and also for the output

**Comment by Nick088Official** [comment]
> > > @nvm01 have you try the no ui version instead of the ui ver ?
> > > now ia am back here, as before i am not using the latest update,
> > > and with the latest update now i am still getting disconnected whenever it goes to Merging section.. i've tried using different account, and i am still getting disconnected, ![Screenshot (7) - Copy](https://private-user-images.githubusercontent.com/182143800/369587501-f23a71e0-9dd9-4896-8e94-bdcca914438f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTYzMzksIm5iZiI6MTcyNjkxNjAzOSwicGF0aCI6Ii8xODIxNDM4MDAvMzY5NTg3NTAxLWYyM2E3MWUwLTlkZDktNDg5Ni04ZTk0LWJkY2NhOTE0NDM4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxMDUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MWEyMDgxNjMyYjQyNzRjNzEwMzBkMjNhOTFhYjY5NThjYTRmOTNhNmE1MmY5YTQwN2JjNmY2MTBlM2VjY2UyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WlXK2UfAuLJbVo1boKs7hBVxIvEGjX965sFa7pFl8rk)
> > > and it has more than 10 minutes video, 2 hours process until it discinected as soon as Merging section started.. it strange because last month it works without promblem even with more than 10 mins videos.. ![Screenshot (8) - Copy](https://private-user-images.githubusercontent.com/182143800/369587635-4d29b0fd-201e-42a5-ba0a-40602031e496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTYzMzksIm5iZiI6MTcyNjkxNjAzOSwicGF0aCI6Ii8xODIxNDM4MDAvMzY5NTg3NjM1LTRkMjliMGZkLTIwMWUtNDJhNS1iYTBhLTQwNjAyMDMxZTQ5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxMDUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmVmNjA4MzU4MzA5ZDhmNDYzYWUwZDE5NzI3MDQ4Zjc5ZjE0MzI2YTFlMjBhNGY5ZDZhOGRmY2M5YjgxNDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7fqOjLiZTv-W0pepCmaefck3aeBkfObQ5kA7fFxWqMU)
> > > @Nick088Official can you test it with 10> min video? but i am not sure its because the duration.. i dont know..
> > 
> > 
> > There will always be a kinda low chance of getting detected, some days ago it used to be in 10 mins now it works good for hours. Also, don't use long videos, max 1 minute long (split the video) for less chance of losing progress (as said in one of the tips, because it swaps the face per frame and that can take alot with much fps and long videos). If you really don't wanna split it you could else be lucky and hope it works for that period of time (as the detection is really random, even before these recent detection changes, there was some that could run it for 4 hours and others who could get detected before, and as seen in #11 I had a report of only 1 person getting banned on 2 accounts, while many others never got banned), or try the [lightning.ai port](https://github.com/Nick088Official/FaceFusion-Online-Ports?tab=readme-ov-file#lightning-ai) that has nothing against web uis & deepfakes. I will try what I can do to make so it's less detectable as possible but just so you know there will always be a chance to get disconnected for disallowed code just like for all other banned things on colab.
> > > and if i can ask.. is there a way to link google drive file (input files) into ui version colab and also set the output into gdrive ? and i think that can help @nvm01 to finish processing without download file directly from UI as before he got disconnected
> > 
> > 
> > Well, yes that's possible for me to connect google drive for the output, but for the inputs i think its not the best way as you can do it only 1 time per run (like you can set the inputs from google drive only one time per everytime you run the cell, then would have to stop running and re run the cell again for every time you change inputs). I think its better i make so u can optionally connect to drive, making a FF_UI_Outputs folder (so a separated one for ui and no ui colab versions), which will have the processed outputs automatically saved here, and ofc you can put the inputs in the webui. Let me know what you think!
> 
> i think thats it maybe i should split my project for non ui ver..
> 
> and as i wanna try UI ver, i would be happy if you can upgrade it because everytime i upload video direct from ui sometimes it get stuck and takes time for me (and for uploading pic, some how it wont load and says "uploading" takes forever for just pic.. and i realized its a bug that i should copy and rename my pic to anything different than fist that failed to upload and it works within a second when i upload again )

That might be related to your internet speed as I personally don't have those issues.

> .. it would be better like if i have file in gdrive and just paste the path to the ui and also for the output

Alright, I will make the same folder for  UI & NO UI version, and give the way to mount drive, and if the user does that automatically use drive for the output path, and give an option to also put the filenames from drive as inputs, but will say you have to stop and run the cell everytime you need to change the inputs.

**Comment by Nick088Official** [comment]
I just added the drive function to the ui too (both use same folder now) and also now both rename 'facefusion' in outputs (like the [FACEFUSION.CORE]) to 'program' trying to help to not get detected. Let me know!

**Comment by Katsukipp** [comment]
> > > > @nvm01 have you try the no ui version instead of the ui ver ?
> > > > now ia am back here, as before i am not using the latest update,
> > > > and with the latest update now i am still getting disconnected whenever it goes to Merging section.. i've tried using different account, and i am still getting disconnected, ![Screenshot (7) - Copy](https://private-user-images.githubusercontent.com/182143800/369587501-f23a71e0-9dd9-4896-8e94-bdcca914438f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTYzMzksIm5iZiI6MTcyNjkxNjAzOSwicGF0aCI6Ii8xODIxNDM4MDAvMzY5NTg3NTAxLWYyM2E3MWUwLTlkZDktNDg5Ni04ZTk0LWJkY2NhOTE0NDM4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxMDUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MWEyMDgxNjMyYjQyNzRjNzEwMzBkMjNhOTFhYjY5NThjYTRmOTNhNmE1MmY5YTQwN2JjNmY2MTBlM2VjY2UyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WlXK2UfAuLJbVo1boKs7hBVxIvEGjX965sFa7pFl8rk)
> > > > and it has more than 10 minutes video, 2 hours process until it discinected as soon as Merging section started.. it strange because last month it works without promblem even with more than 10 mins videos.. ![Screenshot (8) - Copy](https://private-user-images.githubusercontent.com/182143800/369587635-4d29b0fd-201e-42a5-ba0a-40602031e496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTYzMzksIm5iZiI6MTcyNjkxNjAzOSwicGF0aCI6Ii8xODIxNDM4MDAvMzY5NTg3NjM1LTRkMjliMGZkLTIwMWUtNDJhNS1iYTBhLTQwNjAyMDMxZTQ5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxMDUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmVmNjA4MzU4MzA5ZDhmNDYzYWUwZDE5NzI3MDQ4Zjc5ZjE0MzI2YTFlMjBhNGY5ZDZhOGRmY2M5YjgxNDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7fqOjLiZTv-W0pepCmaefck3aeBkfObQ5kA7fFxWqMU)
> > > > @Nick088Official can you test it with 10> min video? but i am not sure its because the duration.. i dont know..
> > > 
> > > 
> > > There will always be a kinda low chance of getting detected, some days ago it used to be in 10 mins now it works good for hours. Also, don't use long videos, max 1 minute long (split the video) for less chance of losing progress (as said in one of the tips, because it swaps the face per frame and that can take alot with much fps and long videos). If you really don't wanna split it you could else be lucky and hope it works for that period of time (as the detection is really random, even before these recent detection changes, there was some that could run it for 4 hours and others who could get detected before, and as seen in #11 I had a report of only 1 person getting banned on 2 accounts, while many others never got banned), or try the [lightning.ai port](https://github.com/Nick088Official/FaceFusion-Online-Ports?tab=readme-ov-file#lightning-ai) that has nothing against web uis & deepfakes. I will try what I can do to make so it's less detectable as possible but just so you know there will always be a chance to get disconnected for disallowed code just like for all other banned things on colab.
> > > > and if i can ask.. is there a way to link google drive file (input files) into ui version colab and also set the output into gdrive ? and i think that can help @nvm01 to finish processing without download file directly from UI as before he got disconnected
> > > 
> > > 
> > > Well, yes that's possible for me to connect google drive for the output, but for the inputs i think its not the best way as you can do it only 1 time per run (like you can set the inputs from google drive only one time per everytime you run the cell, then would have to stop running and re run the cell again for every time you change inputs). I think its better i make so u can optionally connect to drive, making a FF_UI_Outputs folder (so a separated one for ui and no ui colab versions), which will have the processed outputs automatically saved here, and ofc you can put the inputs in the webui. Let me know what you think!
> > 
> > 
> > i think thats it maybe i should split my project for non ui ver..
> > and as i wanna try UI ver, i would be happy if you can upgrade it because everytime i upload video direct from ui sometimes it get stuck and takes time for me (and for uploading pic, some how it wont load and says "uploading" takes forever for just pic.. and i realized its a bug that i should copy and rename my pic to anything different than fist that failed to upload and it works within a second when i upload again )
> 
> That might be related to your internet speed as I personally don't have those issues.
> 
> > .. it would be better like if i have file in gdrive and just paste the path to the ui and also for the output
> 
> Alright, I will make the same folder for UI & NO UI version, and give the way to mount drive, and if the user does that automatically use drive for the output path, and give an option to also put the filenames from drive as inputs, but will say you have to stop and run the cell everytime you need to change the inputs.

thanks by the way

**Comment by Katsukipp** [comment]
> Owner

i've tried latest update and only once i've success processing 15 second video but still.. like @nvm01 it's disconnected as soon as program finished.

and i tried my second try and getting disconnected when "extracting images" progress (this earliest detecton, longest detection for me is on merging section)

i've tried all different google account also,

i thing maybe i'll take a rest for while, i'll keep it up for future update 
once again thanks @Nick088Official

**Comment by Nick088Official** [comment]
> > Owner
> 
> i've tried latest update and only once i've success processing 15 second video but still.. like @nvm01 it's disconnected as soon as program finished.
> 
> and i tried my second try and getting disconnected when "extracting images" progress (this earliest detecton, longest detection for me is on merging section)
> 
> i've tried all different google account also,
> 
> i thing maybe i'll take a rest for while, i'll keep it up for future update once again thanks @Nick088Official

You're welcome, it's kinda random as you see.
